### ISSUE TITLE
Create NES Setup

### ISSUE THREAD

**Issue by paguos** [paguos/mosaic-nes#19]
Replace the placeholder image with a running image of nebula stream.

**Tasks*

- [x] Create models for NES Topology
- [x] Parse topology from config
- [x] Crete custom commands for docker images
- [x] Create docker network for deployment

**Missing**
- [x] Add parent node option for NES worker docker api command
