### ISSUE TITLE
feat(fed): define NES Schema for stream

### ISSUE THREAD

**Issue by paguos** [paguos/mosaic-nes#33]
Define the schema for the "mosaic_vehicles" logical stream. 

**Tasks**
- [x] Create abstraction to create schemas
- [x] Replace placeholder QnV stream
- [x] Replace CSV file in the Docker image
