### ISSUE TITLE
feat: replace CSVSource with ZeroMQSource 

### ISSUE THREAD

**Issue by paguos** [paguos/mosaic-nes#35]
The current implementation uses a CSV source to send data to our stream. The idea is to send data from our RSU using ZeroMQ.

The problem is that in the current version of NebulaStream it is not possible to deploy a ZeroMQ from the RSU.

**Tasks**
- [x] Manage to deploy a ZeroMQ source using the `nesWorker`cli.
- [x] Parse data into a byte buffer 
- [x] Replace the current CSV source
