### ISSUE TITLE
feat(fed): enable NES UI

### ISSUE THREAD

**Issue by paguos** [paguos/mosaic-nes#67]
Start the NES UI with the NES Federate. Creating a container that its linked with the NES Coordinator.

**Tasks**

- [x] Create Docker image for NES UI
- [x] Modify NES Coordinator
- [x] Update Scenario Generator with an UI flag
