### ISSUE TITLE
feat(app): NES-less vehicle sink 

### ISSUE THREAD

**Issue by paguos** [paguos/mosaic-nes#73]
Implement an application that reads the messages from nearby road side units sinks.

**Tasks**
- [ ] Component to register vehicle ip
- [ ] Speed reader application
- [ ] Add extra integration tests
